# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

ccflags-y += -I$(srctree)/drivers/video/fbdev/msm

obj-$(CONFIG_TOUCHSCREEN_NT36XXX_ASUS) += nt36xxx.o
obj-$(CONFIG_TOUCHSCREEN_NT36XXX_FW_UPDATE) += nt36xxx_fw_update.o
